name: Code Quality

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  checks: write
  contents: read

jobs:
  commit-message:
    name: Commit message
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint latest commit message
        if: github.event_name == 'push'
        run: pnpm commitlint --from ${{ github.event.before }} --to ${{ github.sha }} --verbose

      - name: Lint PR commit messages
        if: github.event_name == 'pull_request'
        run: pnpm commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  quality:
    name: Code quality
    uses: ./.github/workflows/quality-checks.yml
    permissions:
      checks: write
      contents: read
